spring:
  application:
    name: CustomerService
  datasource:
    url: jdbc:mysql://localhost:3306/CustomerServiceMicroserviceDB?createDatabaseIfNotExist=true
    username: hamza
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql

server:
  port: 8081
